people = {
    'me': ('He He', 'http://www.umiacs.umd.edu/~hhe/'),
    'hal': ('Hal Daum&eacute III', 'http://www.umiacs.umd.edu/~hal/'),
    'jordan': ('Jordan Boyd-Graber', 'http://www.umiacs.umd.edu/~jbd/'),
    'paul': ('Paul Mineiro', 'http://www.machinedlearnings.com/'),
    'nikos': ('Nikos Karampatziakis', 'http://lowrank.net/nikos/index.html'),
    'alvin': ('Alvin Grissom II', 'http://www.umiacs.umd.edu/~alvin/'),
    'jjm': ('John Morgan', ''),
    'kaiwei': ('Kai-Wei Chang', 'http://kwchang.net'),
    'langford': ('John Langford', 'http://hunch.net/~jl'),
    'xiangyang': ('Xiangyang Liu', 'https://www.linkedin.com/in/xiangyang-liu-59315740'),
    'baras': ('John Baras', 'http://www.isr.umd.edu/~baras/'),
    'lihong': ('Lihong Li', 'http://www.research.rutgers.edu/~lihong'),
    'jasonw': ('Jason D. Williams', 'http://research.microsoft.com/en-us/people/jawillia'),
    'eisner': ('Jason Eisner', 'http://www.cs.jhu.edu/~jason/'),
    'brianna': ('Brianna Satinoff', ''),
    'wan-chi': ('Wan-Chi Siu', 'http://www.eie.polyu.edu/~wcsiu/'),
    'ali': ('Ali Ghodsi', 'http://www.math.uwaterloo.ca/~aghodsib/'),
    'mohit': ('Mohit Iyyer', 'http://www.cs.umd.edu/~miyyer/'),
    }
