people = {
    'me': ('He He', 'http://www.umiacs.umd.edu/~hhe/'),
    'urvashi': ('Urvashi Khandelwal', 'https://nlp.stanford.edu/~urvashik/'),
    'peng': ('Peng Qi', 'http://qipeng.me'),
    'jurafsky': ('Dan Jurafsky', 'https://web.stanford.edu/~jurafsky/'),
    'juncen': ('Juncen Li', ''),
    'robin': ('Robin Jia', 'http://stanford.edu/~robinjia/'),
    'anusha': ('Anusha Balakrishnan', ''),
    'mihail': ('Mihail Eric', 'http://stanford.edu/~meric/'),
    'percy': ('Percy Liang', 'http://cs.stanford.edu/~pliang'),
    'hal': ('Hal Daum&eacute III', 'http://www.umiacs.umd.edu/~hal/'),
    'jordan': ('Jordan Boyd-Graber', 'http://www.umiacs.umd.edu/~jbd/'),
    'paul': ('Paul Mineiro', 'http://www.machinedlearnings.com/'),
    'nikos': ('Nikos Karampatziakis', 'http://lowrank.net/nikos/index.html'),
    'alvin': ('Alvin Grissom II', 'http://www.umiacs.umd.edu/~alvin/'),
    'jjm': ('John Morgan', ''),
    'kaiwei': ('Kai-Wei Chang', 'http://kwchang.net'),
    'langford': ('John Langford', 'http://hunch.net/~jl'),
    'xiangyang': ('Xiangyang Liu', 'https://www.linkedin.com/in/xiangyang-liu-59315740'),
    'baras': ('John Baras', 'http://www.isr.umd.edu/~baras/'),
    'lihong': ('Lihong Li', 'http://www.research.rutgers.edu/~lihong'),
    'jasonw': ('Jason D. Williams', 'http://research.microsoft.com/en-us/people/jawillia'),
    'eisner': ('Jason Eisner', 'http://www.cs.jhu.edu/~jason/'),
    'brianna': ('Brianna Satinoff', ''),
    'wan-chi': ('Wan-Chi Siu', 'http://www.eie.polyu.edu/~wcsiu/'),
    'ali': ('Ali Ghodsi', 'http://www.math.uwaterloo.ca/~aghodsib/'),
    'mohit': ('Mohit Iyyer', 'http://www.cs.umd.edu/~miyyer/'),
    'chenxi': ('Xi Chen', 'https://sites.google.com/site/xichenstephen/'),
    'larry': ('Larry Davis', 'http://www.umiacs.umd.edu/~lsd/'),
    'kwok': ('Kevin Kwok', ''),
    'ross': ('St&eacutephane Ross', 'http://www.cs.cmu.edu/~sross1/'),
    }
