venue = {
    'naacl': ('North American Chapter of the Association for Computational Linguistics', 'NAACL'),
    'iclr': ('International Conference on Learning Representations', 'ICLR'),
    'acl': ('Association for Computational Linguistics', 'ACL'),
    'acl findings': ('Findings of the Association for Computational Linguistics', 'ACL Findings'),
    'eacl': ('The European Chapter of the Association for Computational Linguistics', 'EACL'),
    'eacl findings': ('Findings of the European Chapter of the Association for Computational Linguistics', 'EACL Findings'),
    'emnlp findings': ('Findings of the Empirical Methods in Natural Language Processing', 'EMNLP Findings'),
    'arxiv': ('arXiv', 'arXiv'),
    'emnlp': ('Empirical Methods in Natural Language Processing', 'EMNLP'),
    'fusion': ('International Conference on Information Fusion', 'Fusion'),
    'icc': ('International Conference on Communications', 'ICC'),
    'slt': ('Spoken Lanugage Technology Workshop', 'SLT'),
    'nips': ('Neural Information Processing Systems', 'NeurIPS'),
    'neurips': ('Neural Information Processing Systems', 'NeurIPS'),
    'cvpr': ('Computer Vision and Pattern Recognition', 'CVPR'),
    'icpr': ('International Conference on Pattern Recognition', 'ICPR'),
    'icml': ('International Conference on Machine Learning', 'ICML'),
    'wacv': ('Winter Conference on Applications of Computer Vision', 'WACV'),
    'sigdial': ('Special Interest Group on Discource and Dialogue', 'SigDial'),
    'inlg': ('International Natural Language Generation Conference', 'INLG'),
    'ml4h': ('Machine Learning for Health', 'ML4H'),
    'aaai': ('AAAI Conference on Artificial Intelligence', 'AAAI'),
    # workshop
    'deeplo': ('DeepLo', 'https://sites.google.com/view/deeplo19'),
    'inferning': ('Inferning', 'http://inferning.cs.umass.edu/2012'),
    'adaptive': ('Machine Learning From and For Adaptive User Technologies: From Active Learning & Experimentation to Optimization & Personalization', 'https://sites.google.com/site/mlaihci/'),
    'vis': ('IEEE Transactions on Visualization and Computer Graphics', 'IEEE Vis'),
    # journal
    'jmlr': ('Journal of Machine Learning Research', 'JMLR'),
    'tacl': ('Transaction of Association for Computational Linguistics', 'TACL'),
    'nature': ('Nature', 'Nature'),
    'tmlr': ('Transaction on Machine Learning Research', 'TMLR'),
}
